Remove Moment, use dayjs
AutarkLabs/aragon-profile pull request #41
Opened 2019-06-28 14:56 UTC by chadoh

This follows the lead of aragonUI (https://github.com/aragon/aragon-ui/pull/383), using [dayjs] rather than date-fns as originally planned.

  [dayjs]: https://github.com/iamkun/dayjs

2019-06-28 14:57 UTC, chadoh commented
@Schwartz10 I have not yet tested this. I was hoping to avoid the need for that by setting up some nice tests for all these functions, but that effort proved more difficult than anticipated (see #40).

2019-07-01 15:38 UTC, Schwartz10 requested changes
Hey @chadoh this seems to be "half" working.

The `Tile` components are reading from unix time properly and displaying the right dates: 
<img width="437" alt="image" src="https://user-images.githubusercontent.com/12353734/60448760-4694e780-9bf4-11e9-93a6-d48537d70aa2.png">

But editing dates in the modal components seems to be broken: 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/12353734/60448617-fd449800-9bf3-11e9-94c0-d0715f9b0c7b.png"> - also, it's interesting 

I didn't dig too deep into this, but I'd imagine the [`useDate`](https://github.com/AutarkLabs/aragon-profile/blob/master/src/client/hooks/useDate.js) has something to do with it.

2019-07-03 12:52 UTC, chadoh commented
@Schwartz10 thanks for checking it! I fixed that issue, and I don't see any others when running it locally.

2019-07-08 11:07 UTC, Schwartz10 approved these changes

2019-07-08 12:35 UTC, merged